// LPP Report Language
// Keyed by domain number → { name, tension, about, placements }
// Pattern paragraphs keyed by placement: "1", "2a", "2b", "3"
// Leadership Moment content, assets/limitations tables, and
// Questions to Sit With live in DOMAIN_CONTENT / ORIENTATION_CONTENT in App.jsx

const LANG = {
  1:{ name:"Contribution", tension:"Visibility ↔ Impact",
    about:"Contribution examines how you experience your own impact when the work moves through others rather than through you. As leadership scope grows, your involvement becomes less direct. You shape outcomes through direction, judgment, and the conditions you create rather than through your own output.\n\nWhen visibility drops or credit becomes unclear, this domain surfaces. The question it asks is where your confidence goes when you can no longer see your hand in the result. It shows what you rely on to feel your contribution is real: doing the work yourself, staying close to how it unfolds, whether your role is being understood correctly, or the strength of the thinking behind it.",
    "1":"In this domain, Execution Mode relies on staying closely connected to the work itself. Confidence comes from being able to see how the outcome is taking shape and to step in when it starts to drift. Under pressure, it protects against loss of control by re-engaging directly and making the direction explicit. This keeps the work aligned, but can make it harder to trust others to carry it forward without your involvement.",
    "2a":"In this domain, Orchestration Mode relies on how the work is structured and managed as it moves through others. Confidence comes from knowing the right processes, roles, and expectations are in place to carry the work forward. Under pressure, it protects against breakdown by reinforcing structure and ensuring the work is being handled as intended. This creates consistency and continuity, but can make it harder to allow the work to evolve when it needs to move beyond the original design.",
    "2b":"In this domain, Navigation Mode relies on how your contribution is understood and recognized by others. Confidence comes from knowing your role in shaping the work is visible and interpreted accurately. Under pressure, it protects against being overlooked or misread by managing how your contribution is communicated and perceived. This helps maintain influence and clarity of role, but can make it harder to stay grounded in the work itself without tracking how it reflects on you.",
    "3":"In this domain, Integration Mode relies on the strength of the thinking behind the work rather than direct involvement in it. Confidence comes from knowing the direction is sound and can hold as it moves through others. Under pressure, it protects against attachment to personal contribution by staying focused on what the work requires now. This allows the work to evolve and strengthen over time, but can make it harder to make your thinking legible to others when the work needs clearer direction or attribution."
  },
  2:{ name:"Reasoning", tension:"Correctness ↔ Transparency",
    about:"Reasoning examines what you rely on when you're faced with uncertainty, ambiguity, or challenge and a decision is yours to make or defend. In senior leadership, decisions rarely come with complete information. The question is not just what you conclude, but where you find confidence in your reasoning when the analysis is mixed, assumptions are exposed, or someone pushes back.\n\nWhen credibility is on the line, this domain surfaces. It shows what leaders rely on to feel their reasoning holds: arriving at the right answer, building a well-structured analysis, ensuring their reasoning lands as credible, or making their assumptions and logic clear enough to examine and adapt.",
    "1":"In this domain, Execution Mode relies on arriving at a clear and decisive answer. Confidence comes from being able to determine what is true and move forward with conviction. Under pressure, it protects against uncertainty by closing on a conclusion and reinforcing it so the decision can move ahead. This drives clarity and momentum, but can make it harder to stay open to new information when the reasoning needs further examination.",
    "2a":"In this domain, Orchestration Mode relies on how the reasoning is structured and worked through. Confidence comes from knowing the logic is sound, assumptions are clear, and the analysis holds together end to end. Under pressure, it protects against flawed conclusions by slowing things down and ensuring the reasoning is fully developed. This strengthens the quality of decisions, but can make it harder to move forward when the situation requires acting without complete clarity.",
    "2b":"In this domain, Navigation Mode relies on how your reasoning is interpreted and received by others. Confidence comes from knowing your thinking is understood, credible, and aligned with how others are making sense of the situation. Under pressure, it protects against being dismissed or misunderstood by adjusting how the reasoning is framed and communicated. This helps build alignment and acceptance, but can make it harder to stay anchored in your own line of thinking when it diverges from the room.",
    "3":"In this domain, Integration Mode relies on the strength and adaptability of the underlying logic. Confidence comes from knowing the reasoning can be examined, adjusted, and still hold as new information emerges. Under pressure, it protects against premature conclusions by continuing to test assumptions and refine the thinking. This leads to more resilient decisions, but can make it harder to signal a clear position when others are looking for closure."
  },
  3:{ name:"Authority", tension:"Direct Control ↔ System Trust",
    about:"Authority examines how you hold accountability when work is no longer yours to control directly. As leadership scope expands, decisions move through teams and systems rather than through you. Others carry work that still reflects on your judgment and your name.\n\nWhen delegated work drifts, creates friction, or produces outcomes that differ from expectation, this domain surfaces. It shows what you rely on to feel that accountability is held: your direct involvement, the oversight structure you maintain, whether your leadership is being read correctly by others, or whether the system is strong enough to produce outcomes without your intervention.",
    "1":"In this domain, Execution Mode relies on direct involvement in how outcomes are delivered. Confidence comes from being able to step in, make decisions, and ensure the work reflects your judgment. Under pressure, it protects against loss of control by reasserting ownership and taking a more active role in driving the outcome. This stabilizes results and reinforces accountability, but can make it harder to allow others to fully own the work when they are in position to carry it.",
    "2a":"In this domain, Orchestration Mode relies on how ownership and decisions are structured across people and teams. Confidence comes from knowing roles are clear, decision paths are defined, and accountability is consistently held. Under pressure, it protects against breakdown by tightening how decisions are made and ensuring responsibility is properly assigned. This creates clarity and consistency, but can make it harder to adjust ownership dynamically when the situation calls for more flexibility.",
    "2b":"In this domain, Navigation Mode relies on how your authority is interpreted by others. Confidence comes from knowing your role, involvement, and level of control are being read appropriately in the context of the situation. Under pressure, it protects against being undermined or mispositioned by calibrating how and when you step in. This helps maintain credibility and appropriate influence, but can make it harder to act decisively when the situation requires clearer assertion of authority.",
    "3":"In this domain, Integration Mode relies on how accountability is held across the system rather than through individual control. Confidence comes from knowing ownership is structured in a way that can produce outcomes without your direct intervention. Under pressure, it protects against over-reliance on individual authority by examining how responsibility is distributed and adjusting it where needed. This strengthens the system's ability to hold the work, but can make it harder to provide immediate direction when others are looking for a clear point of ownership."
  },
  4:{ name:"Loyalty", tension:"Your People ↔ The Whole",
    about:"Loyalty examines how you hold responsibility when the interests of your team and the needs of the broader organization pull in different directions. Senior leadership regularly requires decisions that create real cost for the people closest to you, and you may not be able to soften, negotiate, or protect your team from that impact.\n\nWhen those tradeoffs become unavoidable, this domain surfaces. It shows what you rely on to hold that tension: protecting your team, managing how the tradeoff is handled, whether your allegiance is being read correctly by both sides, or what best serves the system as a whole.",
    "1":"In this domain, Execution Mode relies on directly representing and protecting your team. Confidence comes from being able to advocate clearly for their interests and ensure their impact is not overlooked. Under pressure, it protects against your team carrying unacknowledged cost by stepping in and making that impact visible. This ensures your team is represented and supported, but can make it harder to hold the broader tradeoff when the system requires a direction that creates local strain.",
    "2a":"In this domain, Orchestration Mode relies on how the tension between team and organization is worked through. Confidence comes from knowing the tradeoff is being handled in a structured and deliberate way, with both sides clearly understood. Under pressure, it protects against misalignment by ensuring the tradeoff is worked through clearly and the implications are fully understood on both sides. This maintains alignment across the system, but can make it harder to take a clear position when the moment calls for stronger advocacy.",
    "2b":"In this domain, Navigation Mode relies on how your stance is interpreted by both your team and the broader organization. Confidence comes from knowing you are being seen as fair, balanced, and appropriately aligned in both directions. Under pressure, it protects against being misread or misaligned by carefully shaping how your position is communicated. This helps maintain credibility across groups, but can make it harder to take a position that clearly favors one side when the situation requires it.",
    "3":"In this domain, Integration Mode relies on holding the needs of the system as a whole. Confidence comes from knowing the direction serves the broader context, even when it creates local cost. Under pressure, it protects against narrowing to one side by keeping the tradeoff visible and working through it without resolving it prematurely. This supports decisions that hold at the system level, but can make it harder to signal clear support to your team when they are directly affected."
  },
  5:{ name:"Presence", tension:"Reaction ↔ Curiosity",
    about:"Presence examines what happens in real time when challenge or emotional intensity enters a conversation. Leadership regularly creates moments where something unexpected occurs, a position is challenged, or frustration surfaces, and your response is visible and consequential.\n\nWhen pressure arrives without warning, this domain surfaces. It shows what you rely on to stay steady in the moment: addressing the moment directly, structuring the interaction, managing how your response is landing, or staying with the tension long enough to understand it.",
    "1":"In this domain, Execution Mode relies on responding directly to what is happening in the moment. Confidence comes from being able to step in, address the issue, and move the interaction forward. Under pressure, it protects against loss of control by acting quickly to resolve tension and re-establish direction. This keeps conversations focused and moving, but can make it harder to stay with what is emerging when the situation requires more time to unfold.",
    "2a":"In this domain, Orchestration Mode relies on how the interaction is structured and contained. Confidence comes from being able to shape the conversation so it stays productive and on track. Under pressure, it protects against escalation by slowing things down and guiding the exchange into a clearer format. This creates stability in the interaction, but can make it harder to allow the conversation to develop organically when something important has not yet surfaced.",
    "2b":"In this domain, Navigation Mode relies on how you are coming across in the moment. Confidence comes from knowing your tone, timing, and response are being interpreted as steady and appropriate. Under pressure, it protects against being misread or escalating the situation by adjusting how you engage. This helps maintain credibility and composure, but can make it harder to respond directly when the moment calls for greater clarity or candor.",
    "3":"In this domain, Integration Mode relies on staying with what is happening beneath the surface of the interaction. Confidence comes from knowing the moment can be understood more fully before moving to resolution. Under pressure, it protects against reacting too quickly by allowing the tension to unfold and examining what is driving it. This creates space for deeper understanding, but can make it harder to move the conversation forward when others are ready to act."
  }
};


export { LANG };
